# Generated by Django 2.0.6 on 2018-07-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0002_auto_20180711_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesexcel',
            name='docfile',
            field=models.FileField(upload_to='mensajeria/Files/excel'),
        ),
    ]
