# Generated by Django 2.0.6 on 2018-07-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0004_auto_20180714_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesexcel',
            name='docfile',
            field=models.FileField(upload_to='excel/'),
        ),
    ]
