# Generated by Django 2.0.6 on 2018-07-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0006_fotoperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoperfil',
            name='name',
            field=models.CharField(default='foto', max_length=50),
        ),
    ]
